spring:
  datasource:
    url: jdbc:mysql://${dev.mysql.host}:${dev.mysql.port}/${dev.mysql.dbname}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${dev.mysql.username}
    password: ${dev.mysql.password}
  profiles:
    include: private
config:
  connect:
    timeout: 5000