spring:
  datasource:
    url: jdbc:mysql://${dev.mysql.host}:${dev.mysql.port}/${dev.mysql.dbname}?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${dev.mysql.username}
    password: ${dev.mysql.password}
  profiles:
    include: private
config:
  connect:
    timeout: 5000
  security:
    credentials:
      expiration: 900 # 15min
      refresh: 600 # 10min
mybatis:
  mapperLocations: classpath:daoImpl/*Mapper.xml